>>> In function foo:
wrong-calls.hlt:4: error, HILTI functions cannot have parameter of type tuple<*>


1 error found
