A
hilti: uncaught exception, myException2 with argument hallo (from throw.hlt:14)
