>>> e = new myException "hello"
wrong-new.hlt:10: error, exception type does not take an argument

wrong-new.hlt: 1 error found during validating
