>>> return.result 42
wrong-returns.hlt:5: error, void function returns a value

wrong-returns.hlt: 1 error found during validating
