>>> return.result 42
wrong-returns.hlt:5: error, void function returns a value


1 error found
