RUN 1
hilti: uncaught exception in worker thread, DivisionByZero (from exceptions.hlt:15)
hilti: uncaught exception, ThreadException (from /da/home/robin/work/binpacpp/hilti/libhilti/threading.c:404)
RUN 2
hilti: uncaught exception in worker thread, DivisionByZero (from exceptions.hlt:15)
hilti: uncaught exception, ThreadException (from /da/home/robin/work/binpacpp/hilti/libhilti/threading.c:404)
RUN 3
hilti: uncaught exception in worker thread, DivisionByZero (from exceptions.hlt:15)
hilti: uncaught exception, ThreadException (from /da/home/robin/work/binpacpp/hilti/libhilti/threading.c:404)
RUN 4
hilti: uncaught exception in worker thread, DivisionByZero (from exceptions.hlt:15)
hilti: uncaught exception, ThreadException (from /da/home/robin/work/binpacpp/hilti/libhilti/threading.c:404)
RUN 5
hilti: uncaught exception in worker thread, DivisionByZero (from exceptions.hlt:15)
hilti: uncaught exception, ThreadException (from /da/home/robin/work/binpacpp/hilti/libhilti/threading.c:404)
